## you probably need to change or comment or uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
# tools scriptsdir resourcesdir
tools: "PIPELINE_HOME/resources/tools.yaml"
clusterjson: "PIPELINE_HOME/resources/cluster.json"
scriptsdir: "PIPELINE_HOME/workflow/scripts"
resourcesdir: "PIPELINE_HOME/resources"
#
# tab delimited samples file ... should have the following 3 columns
# sampleName	path_to_R1_fastq	path_to_R2_fastq
#
samplemanifest: "WORKDIR/samples.tsv"
genome: "mm10"
multimapping: 4
#
#
#
hg38:
  indexdir: "/data/CCBR_Pipeliner/db/PipeDB/Indices/hg38_basic/indexes"
  blacklistFa: "PIPELINE_HOME/resources/blacklistFa/hg38.blacklist.fa.gz"
  tssBed: "PIPELINE_HOME/resources/tssBed/hg38_tssbeds.tar.gz"
  homermotif: "PIPELINE_HOME/resources/motif/HOCOMOCOv11_full_HUMAN_mono_homer_format_0.001.motif"
  mememotif: "PIPELINE_HOME/resources/motif/HOCOMOCOv11_core_HUMAN_mono_meme_format.tar.gz"
  effectiveGenomeSize: 2700000000
  fripextra: 
    dhsbed: "PIPELINE_HOME/resources/frip/hg38.DHS.bed.gz"
    promoterbed: "PIPELINE_HOME/resources/frip/hg38.promoters.bed.gz"
    enhancerbed: "PIPELINE_HOME/resources/frip/hg38.enhancers.bed.gz"
hg19:
  indexdir: "/data/CCBR_Pipeliner/db/PipeDB/Indices/hg19_basic/indexes"
  blacklistFa: "PIPELINE_HOME/resources/blacklistFa/hg19.blacklist.fa.gz"
  tssBed: "PIPELINE_HOME/resources/tssBed/hg19_tssbeds.tar.gz"
  homermotif: "PIPELINE_HOME/resources/motif/HOCOMOCOv11_full_HUMAN_mono_homer_format_0.001.motif"
  mememotif: "PIPELINE_HOME/resources/motif/HOCOMOCOv11_core_HUMAN_mono_meme_format.tar.gz"
  effectiveGenomeSize: 2700000000
  fripextra: 
    dhsbed: "PIPELINE_HOME/resources/frip/hg19.DHS.bed.gz"
    promoterbed: "PIPELINE_HOME/resources/frip/hg19.promoters.bed.gz"
    enhancerbed: "PIPELINE_HOME/resources/frip/hg19.enhancers.bed.gz"
mm10:
  indexdir: "/data/CCBR_Pipeliner/db/PipeDB/Indices/mm10_basic/indexes"
  blacklistFa: "PIPELINE_HOME/resources/blacklistFa/mm10.blacklist.fa.gz"
  tssBed: "PIPELINE_HOME/resources/tssBed/mm10_tssbeds.tar.gz"
  homermotif: "PIPELINE_HOME/resources/motif/HOCOMOCOv11_full_MOUSE_mono_homer_format_0.001.motif"
  mememotif: "PIPELINE_HOME/resources/motif/HOCOMOCOv11_core_MOUSE_mono_meme_format.tar.gz"
  effectiveGenomeSize: 1870000000
  fripextra:
    dhsbed: "PIPELINE_HOME/resources/frip/mm10.DHS.bed.gz"
    promoterbed: "PIPELINE_HOME/resources/frip/mm10.promoters.bed.gz"
    enhancerbed: "PIPELINE_HOME/resources/frip/mm10.enhancers.bed.gz"
macs2:
  extsize: 200
  shiftsize: 100
  annotatePeaks: True
genrich:
  s: 5
  m: 6
  q: 1
  l: 100
  g: 100
  d: 100
  annotatePeaks: True
# master container
# masterdocker: "docker://nciccbr/ccbr_atacseq:v0.1.29"
masterdocker: "docker://nciccbr/ccbr_atacseq:v1.7"
fastqcdocker: "docker://nciccbr/ccbr_fastqc_0.11.9:v1.1"

