## you probably need to change or comment or uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
# tools scriptsdir resourcesdir
tools: "PIPELINE_HOME/resources/tools.yaml"
clusterjson: "PIPELINE_HOME/resources/cluster.json"
scriptsdir: "PIPELINE_HOME/workflow/scripts"
resourcesdir: "PIPELINE_HOME/resources"
#
# tab delimited samples file ... should have the following 3 columns
# sampleName	path_to_R1_fastq	path_to_R2_fastq
#
samples: "WORKDIR/samples.tsv"
genome: "hg38"
multimapping: 4
#
#
#
hg38:
  indexdir: "/data/CCBR_Pipeliner/db/PipeDB/Indices/hg38_basic/indexes"
macs2:
  extsize: 200
  shiftsize: 100
genrich:
  s: 5
  m: 6
  q: 1
  l: 200
  g: 200
# master container
# masterdocker: "docker://nciccbr/ccbr_atacseq:v0.1.29"
masterdocker: "docker://nciccbr/ccbr_atacseq:v1.3.1"
fastqcdocker: "docker://nciccbr/ccbr_fastqc_0.11.9:v1.1"

